server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1111
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  redis:
    host: 182.92.183.11
  rabbitmq:
    host: 182.92.183.11
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo